name: Rust Check

on:
  push:

env:
  RUSTFLAGS: -D warnings

jobs:
  build:
    name: Build & Test
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
        env:
          RUSTFLAGS: -D warnings
          RUST_BACKTRACE: 1
      - name: Run tests
        run: cargo test --all --verbose

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        run: |
          rustup update --no-self-update stable
          rustup component add rustfmt clippy
      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Check formating
        run: |
          cargo fmt --all -- --check
      - name: Check clippy
        run: |
          cargo clippy --no-deps